server:
  port: 8080  # Gateway akan diakses di http://localhost:8080

spring:
  cloud:
    gateway:
      routes:
        # ROUTE untuk UserService
        - id: user-service
          uri: http://userservice:8081
          predicates:
            - Path=/users/**,/register,/login,/logout,/me

        # ROUTE untuk VaksinasiService
        - id: vaksinasi-service
          uri: http://vaksinasiservice:8082
          predicates:
            - Path=/vaksinasi/**
